id: 'contour'
center:
  lon: 9.5554
  lat: 47.1660
  zoom: 14
bounds:
  minLon: 9.471078
  maxLon: 9.636217
  minLat: 47.04774
  maxLat: 47.27128
  minZoom: 12
  maxZoom: 20
layers:
  - id: 'aster_dem'
    type: 'geometry'
    minZoom: 12
    maxZoom: 20
    queries:
      - SELECT id, hstore('elevation', elevation::text) as tags, wkb_geometry as geom FROM aster_dem
