name: Deploy snapshot

on:
  push:
    branches:
      - main

jobs:
  deploy-snapshot:
    name: Deploy snapshot
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/v')"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: apache.snapshots.https
          server-username: NEXUS_USER
          server-password: NEXUS_PW
          gpg-private-key: ${{ secrets.BAREMAPS_GPG_SECRET_KEY }}

      - name: Set up GPG
        run: |
          echo "${{ secrets.BAREMAPS_GPG_SECRET_KEY }}" | gpg --batch --import
          gpg --list-keys
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Publish snapshots on Apache Nexus
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
        run: |
          ./mvnw deploy -DskipTests -Dmaven.javadoc.skip=true -B -V
